name=PILOT_KWS
version=1.0.0
author=RADII Team
maintainer=splash0e
sentence=Custom offline wake-word (PILOT) detection for ESP32 using INT8 TensorFlow Lite Micro.
paragraph=Runs a custom-trained keyword-spotting model locally on ESP32 with INMP441 I2S microphone input.
category=Signal Input/Output
url=https://github.com/splash0e/PILOTKWS
architectures=esp32
