name=PILOT_KWS_Library
version=1.0.0
author=RADII
maintainer=RADII
sentence=Custom PILOT keyword spotting library for ESP32.
paragraph=Offline keyword spotting using a custom INT8 TensorFlow Lite Micro model.
category=Signal Input/Output
architectures=esp32
